//
//  DetailsViewController.swift
//  Vyayamshala
//
//  Created saket bhushan on 23/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailsViewController: UIViewController, DetailsViewProtocol {

	var presenter: DetailsPresenterProtocol?
    
    @IBOutlet weak var imgView: UIImageView!
    
    @IBOutlet weak var headingLbl: UILabel!
    
    
    @IBOutlet weak var descriptionTextView: UITextView!
    
    var fitnessDetails: FoodNFitnessModel!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "Details"
        if let url = URL(string: fitnessDetails.imageUrl) {
         self.imgView.sd_setImage(with: url)
        }
        self.headingLbl.text = fitnessDetails.imageTitle
        self.descriptionTextView.text = fitnessDetails.description
    }
}
