//
//  DetailsRouter.swift
//  Vyayamshala
//
//  Created saket bhushan on 23/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailsRouter: DetailsWireframeProtocol {
    
    weak var viewController: DetailsViewController?
    
    static func createModule() -> DetailsViewController {
        let view = DetailsViewController.createInstance() as! DetailsViewController
        let router = DetailsRouter()
        let presenter = DetailsPresenter(interface: view, router: router)
        view.presenter = presenter
        router.viewController = view
        return view
    }
}
