//
//  FitnessAndDietPresenter.swift
//  Vyayamshala
//
//  Created saket bhushan on 21/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FitnessAndDietPresenter: FitnessAndDietPresenterProtocol {

    weak private var view: FitnessAndDietViewProtocol?
    var interactor: FitnessAndDietInteractorProtocol?
    private let router: FitnessAndDietWireframeProtocol

    init(interface: FitnessAndDietViewProtocol, interactor: FitnessAndDietInteractorProtocol?, router: FitnessAndDietWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
