//
//  FitnessAndDietViewController.swift
//  Vyayamshala
//
//  Created saket bhushan on 21/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum FoodNFitness {
    case Food
    case Fitness
}

class FitnessAndDietViewController: UIViewController, FitnessAndDietViewProtocol {

	var presenter: FitnessAndDietPresenterProtocol?
    var option: FoodNFitness!
    
    @IBOutlet weak var collectionView: UICollectionView!
    
    var dataList: [FoodNFitnessModel]!
    
    
	override func viewDidLoad() {
        super.viewDidLoad()
        if option == FoodNFitness.Fitness {
            self.title = "Fitness"
            self.dataList = Fitness.getMaleList()
        } else {
            self.dataList = Food.getVegList()
            self.title = "Food"
        }
    }
}

extension FitnessAndDietViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    public func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return self.dataList.count
    }
    
    public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "FoodNFitnessCollectionViewCell", for: indexPath) as! FoodNFitnessCollectionViewCell
        cell.setData(model: self.dataList[indexPath.row])
        return cell
    }
    
    public func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize
    {
        let size = UIScreen.main.bounds.width/2
        return CGSize(width: size, height: size)
    }
}
