//
//  FitnessAndDietRouter.swift
//  Vyayamshala
//
//  Created saket bhushan on 21/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FitnessAndDietRouter: FitnessAndDietWireframeProtocol {
    
    weak var viewController: FitnessAndDietViewController?
    
    static func createModule() -> FitnessAndDietViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FitnessAndDietViewController.createInstance() as! FitnessAndDietViewController
        let interactor = FitnessAndDietInteractor()
        let router = FitnessAndDietRouter()
        let presenter = FitnessAndDietPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
