//
//  FitnessAndDietViewController.swift
//  Vyayamshala
//
//  Created saket bhushan on 21/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum FoodNFitness {
    case Food
    case Fitness
}

class FitnessAndDietViewController: UIViewController, FitnessAndDietViewProtocol {

	var presenter: FitnessAndDietPresenterProtocol?
    var option: FoodNFitness!
    
    @IBOutlet weak var collectionView: UICollectionView!
    
    @IBOutlet weak var segmentControl: UISegmentedControl!
    
    var dataList: [FoodNFitnessModel]!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        if option == FoodNFitness.Fitness {
            self.title = "Fitness"
            self.dataList = Fitness.getMaleList()
            self.segmentControl.setTitle("Male", forSegmentAt: 0)
            self.segmentControl.setTitle("Female", forSegmentAt: 1)
        } else {
            self.title = "Food"
            self.segmentControl.setTitle("Veg", forSegmentAt: 0)
            self.segmentControl.setTitle("Non-Veg", forSegmentAt: 1)
            
            self.dataList = Food.getVegList()
            
        }
    }
    
    
    
    @IBAction func segmentControlDidChange(_ sender: UISegmentedControl) {
        if option == FoodNFitness.Fitness {
            if sender.selectedSegmentIndex == 0 {
                self.dataList = Fitness.getMaleList()
            } else {
                self.dataList = Fitness.getFemaleList()
            }
        } else {
            if sender.selectedSegmentIndex == 0 {
                self.dataList = Food.getVegList()
            } else {
                self.dataList = Food.getNonVegList()
            }
        }
        self.collectionView.reloadData()
        if (self.collectionView?.scrollsToTop)! {
            self.collectionView?.scrollToItem(at: IndexPath(row: 0, section: 0),
                                              at: .top,
                                              animated: false)
        }
    }
    
}

extension FitnessAndDietViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    public func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return self.dataList.count
    }
    
    public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "FoodNFitnessCollectionViewCell", for: indexPath) as! FoodNFitnessCollectionViewCell
        cell.setData(model: self.dataList[indexPath.row])
        return cell
    }
    
    public func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize
    {
        let size = (9*UIScreen.main.bounds.width)/10
        return CGSize(width: size, height: size/2)
    }
}
