//
//  FitnessAndDietInteractor.swift
//  Vyayamshala
//
//  Created saket bhushan on 21/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FitnessAndDietInteractor: FitnessAndDietInteractorProtocol {

    weak var presenter: FitnessAndDietPresenterProtocol?
}
