//
//  FitnessAndDietPresenter.swift
//  Vyayamshala
//
//  Created saket bhushan on 21/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FitnessAndDietPresenter: FitnessAndDietPresenterProtocol {
    weak private var view: FitnessAndDietViewProtocol?
    private let router: FitnessAndDietWireframeProtocol

    init(interface: FitnessAndDietViewProtocol, router: FitnessAndDietWireframeProtocol) {
        self.view = interface
        self.router = router
    }

    func didSeletItem(fitness: FoodNFitnessModel) {
        self.router.routeToDetails(fitness: fitness)
    }
}
