//
//  GymAlternativeHomeRemediesInteractor.swift
//  Vyayamshala
//
//  Created saket bhushan on 20/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GymAlternativeHomeRemediesInteractor: GymAlternativeHomeRemediesInteractorProtocol {

    weak var presenter: GymAlternativeHomeRemediesPresenterProtocol?
}
