//
//  GymAlternativeHomeRemediesRouter.swift
//  Vyayamshala
//
//  Created saket bhushan on 20/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GymAlternativeHomeRemediesRouter: GymAlternativeHomeRemediesWireframeProtocol {
    
    weak var viewController: GymAlternativeHomeRemediesViewController?
    
    static func createModule() -> GymAlternativeHomeRemediesViewController {
        let view = GymAlternativeHomeRemediesViewController.createInstance() as! GymAlternativeHomeRemediesViewController
        let interactor = GymAlternativeHomeRemediesInteractor()
        let router = GymAlternativeHomeRemediesRouter()
        let presenter = GymAlternativeHomeRemediesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
