//
//  GymAlternativeHomeRemediesViewController.swift
//  Vyayamshala
//
//  Created saket bhushan on 20/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum GymAlt {
    case HomeRemedy
    case GymAletnative
}

class GymAlternativeHomeRemediesViewController: UIViewController, GymAlternativeHomeRemediesViewProtocol {

	var presenter: GymAlternativeHomeRemediesPresenterProtocol?
    
    var option: GymAlt!
    
    var dataList: [Model]!
    
    @IBOutlet weak var collectionView: UICollectionView!
    
    let cellIdentifier = "GymAletnativesHomeRemediesCollectionViewCell"
    
    let size = UIScreen.main.bounds.width/3
    
    override func viewDidLoad() {
        super.viewDidLoad()
        if option == GymAlt.HomeRemedy {
            self.dataList = HomeRemedy.getData()
        }
        self.dataList = GymAlternatives.getData()
    }
}

extension GymAlternativeHomeRemediesViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
 
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return dataList.count
    }
    
    public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: self.cellIdentifier, for: indexPath) as! GymAletnativesHomeRemediesCollectionViewCell
        cell.layer.cornerRadius = self.size/2
        cell.setData(model: dataList[indexPath.row])
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: self.size, height: self.size)
    }
}
