//
//  GymAlternativeHomeRemediesPresenter.swift
//  Vyayamshala
//
//  Created saket bhushan on 20/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GymAlternativeHomeRemediesPresenter: GymAlternativeHomeRemediesPresenterProtocol {
    weak private var view: GymAlternativeHomeRemediesViewProtocol?
    private let router: GymAlternativeHomeRemediesWireframeProtocol

    init(interface: GymAlternativeHomeRemediesViewProtocol, router: GymAlternativeHomeRemediesWireframeProtocol) {
        self.view = interface
        self.router = router
    }

}
