//
//  GymAlternativeHomeRemediesProtocols.swift
//  Vyayamshala
//
//  Created saket bhushan on 20/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

protocol Model: class {
    var entity: String? {get set}
    var description: String? {get set}
}

//MARK: Wireframe -
protocol GymAlternativeHomeRemediesWireframeProtocol: class {

}
//MARK: Presenter -
protocol GymAlternativeHomeRemediesPresenterProtocol: class {

}

//MARK: View -
protocol GymAlternativeHomeRemediesViewProtocol: class {

  var presenter: GymAlternativeHomeRemediesPresenterProtocol?  { get set }
}
