//
//  GymAlternativeHomeRemediesViewController.swift
//  Vyayamshala
//
//  Created saket bhushan on 20/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum GymAlt {
    case HomeRemedy
    case GymAletnative
}

class GymAlternativeHomeRemediesViewController: UIViewController, GymAlternativeHomeRemediesViewProtocol {

	var presenter: GymAlternativeHomeRemediesPresenterProtocol?
    
    var option: GymAlt!
    
    var dataList: [Model]!
    
    @IBOutlet weak var collectionView: UICollectionView!
    
    @IBOutlet weak var headerLbl: UILabel!
    
    @IBOutlet weak var descriptionTextView: UITextView!
    
    
    let cellIdentifier = "GymAletnativesHomeRemediesCollectionViewCell"
    
    let size = UIScreen.main.bounds.width/3
    
    override func viewDidLoad() {
        super.viewDidLoad()
        if option == GymAlt.HomeRemedy {
            self.title = "Home Remedies"
            self.dataList = HomeRemedy.getData()
        } else {
            self.title = "Gym Alternatives"
            self.dataList = GymAlternatives.getData()
        }
        self.setUIData(model: self.dataList[0])
        
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.30) {
            self.collectionView.reloadData()
        }
        
    }
    
    func setUIData(model: Model) {
        self.headerLbl.text = model.entity
        self.descriptionTextView.text = model.description
    }
    
}

extension GymAlternativeHomeRemediesViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return dataList.count
    }
    
    public func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: self.cellIdentifier, for: indexPath) as! GymAletnativesHomeRemediesCollectionViewCell
        cell.setData(model: dataList[indexPath.row])
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: self.size, height: self.size)
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        self.setUIData(model: self.dataList[indexPath.row])
    }
}
