//
//  HomePresenter.swift
//  Vyayamshala
//
//  Created saket bhushan on 16/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter {
    
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension HomePresenter: HomePresenterProtocol {
    
    func peopleAndStories() {
        self.router.routeToPeopleAndStories()
    }
    
    func gymAlternatives(option: GymAlt) {
        self.router.routeToGymAlternatives(option: option)
    }
    
    func foodNFitness(option: FoodNFitness) {
        self.router.routeToFoodNFitnerss(option: option)
    }
}
