//
//  HomeRouter.swift
//  Vyayamshala
//
//  Created saket bhushan on 16/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeRouter {
    
    weak var viewController: HomeViewController?
    
    static func createModule(vc: HomeViewController) /*-> HomeViewController */{
        // Change to get view from storyboard if not using progammatic UI
        let view = vc //HomeViewController(nibName: nil, bundle: nil)
        let interactor = HomeInteractor()
        let router = HomeRouter()
        let presenter = HomePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        //return view
    }
}

extension HomeRouter: HomeWireframeProtocol {
    
    func routeToPeopleAndStories() {
     let vc = PeopleAndStoriesRouter.createModule()
     self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func routeToGym() {
        
    }
    
    func routeToGymAlternatives() {
        let vc = GymAlternativeHomeRemediesRouter.createModule()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func routeToFood() {
        
    }
    
    func routeToHomeRemedies() {
        
    }
}
