//
//  PeopleAndStoriesRouter.swift
//  Vyayamshala
//
//  Created saket bhushan on 19/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PeopleAndStoriesRouter: PeopleAndStoriesWireframeProtocol {
    
    weak var viewController: PeopleAndStoriesViewController?
    
    static func createModule() -> PeopleAndStoriesViewController {
        let view = PeopleAndStoriesViewController.createInstance() as! PeopleAndStoriesViewController
        let interactor = PeopleAndStoriesInteractor()
        let router = PeopleAndStoriesRouter()
        let presenter = PeopleAndStoriesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
