//
//  PeopleAndStoriesInteractor.swift
//  Vyayamshala
//
//  Created saket bhushan on 19/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PeopleAndStoriesInteractor: PeopleAndStoriesInteractorProtocol {

    weak var presenter: PeopleAndStoriesPresenterProtocol?
}
