//
//  PeopleAndStoriesViewController.swift
//  Vyayamshala
//
//  Created saket bhushan on 19/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PeopleAndStoriesViewController: UIViewController, PeopleAndStoriesViewProtocol {

	var presenter: PeopleAndStoriesPresenterProtocol?
    var peopleStoriesList = [PeopleNameStories]()
    

	override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "People And Stories"
        self.peopleStoriesList = PeopleNameStories.getPeopleNameAndStories()        
    }
}

// StoriesTableViewCell
extension PeopleAndStoriesViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.peopleStoriesList.count + 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        if indexPath.row == 0 {
          let cell = tableView.dequeueReusableCell(withIdentifier: "PeopleScrollTableViewCell", for: indexPath) as! PeopleScrollTableViewCell
            return cell
        } else {
           let cell = tableView.dequeueReusableCell(withIdentifier: "StoriesTableViewCell", for: indexPath) as! StoriesTableViewCell
            cell.setData(peopleNameStories: self.peopleStoriesList[indexPath.row - 1])
            return cell
        }
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if indexPath.row == 0 {
         return 200
        }
        return UITableViewAutomaticDimension
    }
}
