//
//  PeopleAndStoriesPresenter.swift
//  Vyayamshala
//
//  Created saket bhushan on 19/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PeopleAndStoriesPresenter: PeopleAndStoriesPresenterProtocol {

    weak private var view: PeopleAndStoriesViewProtocol?
    var interactor: PeopleAndStoriesInteractorProtocol?
    private let router: PeopleAndStoriesWireframeProtocol

    init(interface: PeopleAndStoriesViewProtocol, interactor: PeopleAndStoriesInteractorProtocol?, router: PeopleAndStoriesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
