//
//  PeopleAndStoriesProtocols.swift
//  Vyayamshala
//
//  Created saket bhushan on 19/07/18.
//  Copyright © 2018 saket bhushan. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PeopleAndStoriesWireframeProtocol: class {

}
//MARK: Presenter -
protocol PeopleAndStoriesPresenterProtocol: class {

}

//MARK: Interactor -
protocol PeopleAndStoriesInteractorProtocol: class {

  var presenter: PeopleAndStoriesPresenterProtocol?  { get set }
}

//MARK: View -
protocol PeopleAndStoriesViewProtocol: class {

  var presenter: PeopleAndStoriesPresenterProtocol?  { get set }
}
